---
language: node_js
node_js:
  - "11.15"

addons:
  apt:
    packages:
      - xvfb
      - mono-complete

before_install:
  - npm run dependencies

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install

script:
  - npm test
  - npm run make

matrix:
  include:
    - os: linux
      dist: xenial
    - os: windows
