---
language: node_js
node_js:
  - "11.15"

addons:
  apt:
    packages:
      - xvfb
      - mono-complete
      - ffmpeg
      - wavpack
      - libsox-fmt-all
      - sox
      - shntool
      - mp3splt
      - libav-tools
      - fakeroot

before_script:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - npm run make
  - npm test

matrix:
  include:
    - os: linux
      dist: xenial
      before_install:
        - npm run dependencies
    - os: windows
