jobs:
  - job: Windows
    pool:
      vmImage: "windows-2019"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "10.x"
        displayName: "Install Node.js"
      - script: npm install
        displayName: "Installing App Dependencies"
      - script: npm run ap_download:windows
        displayName: "Installing AP"
      - script: npm run lint
        displayName: "Lint project"
      - script: npm test
        displayName: "Unit tests"
      - script: npm run e2e
        displayName: "End to end tests"
      - script: npm run electron:windows
        displayName: "Build project"
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "$(Build.SourcesDirectory)/release/AP Desktop 4.0.0.exe"
          artifactName: ap-desktop-windows
        displayName: "Publish build files"
  - job: Linux
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "10.x"
        displayName: "Install Node.js"
      - script: npm install
        displayName: "Installing App Dependencies"
      - script: npm run ap_download:linux
        displayName: "Installing AP"
      - script: npm run lint
        displayName: "Lint project"
      - script: npm test
        displayName: "Unit tests"
      - script: npm run e2e
        displayName: "End to end tests"
      - script: npm run electron:linux
        displayName: "Build project"
