name: ap-desktop # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: "1.2.1" # just for humans, typically '1.2+git' or '1.3.2'
summary: GUI for terminal based program analysis_programs.exe # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
type: app

apps:
  ap-desktop:
    command: ../out/ap-desktop-linux-x64/ap-desktop
    common-id: org.ecosounds.ap-desktop
